### ISSUE TITLE
Error while executing 3_runCntk.py

### ISSUE THREAD

**Issue by AkshayAgarwal007** [Azure/ObjectDetectionUsingCntk#5]
I am getting the following error while executing 3_runCntk.py.

![image](https://cloud.githubusercontent.com/assets/8170214/22303859/2358dd3e-e35b-11e6-9b11-5d580dc992f8.png)

**Comment by PatrickBue** [comment]
My guess is that this is caused by the new CNTK 2.0 not being fully backwards compatible. Try installing an older version of CNTK instead, e.g. 1.7.2: https://github.com/Microsoft/CNTK/releases/tag/v1.7.2
I am planning on upgrading this tutorial to the newest CNTK + python wrappers, but won't be able to work on this for another 4-6 weeks.

**Comment by AkshayAgarwal007** [comment]
It' working fine with the CNTK 2.0 version that came pre-installed with Azure DSVM.
